# Generated by Django 5.2.3 on 2025-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='banner_pics/'),
        ),
    ]
