# Generated by Django 5.2.3 on 2025-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yap',
            options={},
        ),
        migrations.AddField(
            model_name='yap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yap_pics/'),
        ),
    ]
